---
instance_groups:
- azs:
  - z1
  instances: 1
  jobs:
  - name: docker
    release: docker
  - name: login_banner
    release: os-conf
    properties:
      login_banner:
        text: |
          Welcome to jump.bosh-lite.local!
  - name: jump
    release: demo-jump
    properties:
      env:
        BOSH_ENVIRONMENT: 192.168.50.4
        BOSH_CA_CERT: |
          -----BEGIN CERTIFICATE-----
          MIIDtzCCAp+gAwIBAgIJAMZ/qRdRamluMA0GCSqGSIb3DQEBBQUAMEUxCzAJBgNV
          BAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJbnRlcm5ldCBX
          aWRnaXRzIFB0eSBMdGQwIBcNMTYwODI2MjIzMzE5WhgPMjI5MDA2MTAyMjMzMTla
          MEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIEwpTb21lLVN0YXRlMSEwHwYDVQQKExhJ
          bnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
          ggEKAoIBAQDN/bv70wDn6APMqiJZV7ESZhUyGu8OzuaeEfb+64SNvQIIME0s9+i7
          D9gKAZjtoC2Tr9bJBqsKdVhREd/X6ePTaopxL8shC9GxXmTqJ1+vKT6UxN4kHr3U
          +Y+LK2SGYUAvE44nv7sBbiLxDl580P00ouYTf6RJgW6gOuKpIGcvsTGA4+u0UTc+
          y4pj6sT0+e3xj//Y4wbLdeJ6cfcNTU63jiHpKc9Rgo4Tcy97WeEryXWz93rtRh8d
          pvQKHVDU/26EkNsPSsn9AHNgaa+iOA2glZ2EzZ8xoaMPrHgQhcxoi8maFzfM2dX2
          XB1BOswa/46yqfzc4xAwaW0MLZLg3NffAgMBAAGjgacwgaQwHQYDVR0OBBYEFNRJ
          PYFebixALIR2Ee+yFoSqurxqMHUGA1UdIwRuMGyAFNRJPYFebixALIR2Ee+yFoSq
          urxqoUmkRzBFMQswCQYDVQQGEwJBVTETMBEGA1UECBMKU29tZS1TdGF0ZTEhMB8G
          A1UEChMYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkggkAxn+pF1FqaW4wDAYDVR0T
          BAUwAwEB/zANBgkqhkiG9w0BAQUFAAOCAQEAoPTwU2rm0ca5b8xMni3vpjYmB9NW
          oSpGcWENbvu/p7NpiPAe143c5EPCuEHue/AbHWWxBzNAZvhVZBeFirYNB3HYnCla
          jP4WI3o2Q0MpGy3kMYigEYG76WeZAM5ovl0qDP6fKuikZofeiygb8lPs7Hv4/88x
          pSsZYBm7UPTS3Pl044oZfRJdqTpyHVPDqwiYD5KQcI0yHUE9v5KC0CnqOrU/83PE
          b0lpHA8bE9gQTQjmIa8MIpaP3UNTxvmKfEQnk5UAZ5xY2at5mmyj3t8woGdzoL98
          yDd2GtrGsguQXM2op+4LqEdHef57g7vwolZejJqN776Xu/lZtCTp01+HTA==
          -----END CERTIFICATE-----
      users:
      - name: dpb587
        public_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGUHLA4SIZ1chp7uj8ejXDERnxL1q+BK08yeh+xewQGyhuzTD7YJtzofT3ctLNSrUNJQI+w50sDhdeNkI9fOaX8BxerRYW9osw4Yr0IWesFhtdmSI6WvpiEKp9Tp66tiZAcnHoxujrfVatU1Pqv+u383s24dn/DJJ0osLabFgQMQHWH0E4H/JCZUUkIwAtrg5ssSP/aPKl17mGPbMKYhM8O9su9l6Vu9tgOBdz4oFEFAGoPpU5kLd/tfcSqmhcArF7dHLLLbuvkSFPh0fZJTFThNDCBD46M9xNg6ycSXDi6Qi4kx6QVpbosUudNazsY7jtC4zx11sR2+vveoynbjA893cnF43tz/2CxN/3ljfxc8JOotqN2qY54G9wBFtYDBuHtJpuxnY6i87DWI4SS6FyqZcjOIZcKfrlu7FSpqeVI6VdP0g72lD4So423/gIbLWFK9zG/kKRw5zMxf2SJ3xNnWygq3Tw4vOgWQWmwhONPNAaWaL0lZ/0F1crijUgdji5+2HUHcKvcVLIIClh3v53LOirK/sXg6mFWHerFTXZ38MS5b7s7cCFyOse/nPlBNuKY50cIHC0IhmSgUfdXb2WIPSgd5XBhB86I30wotdlMdMpXzdVdjdG3aQcXjppjJ7VXyGduoTJX0xMu3Oi/ewoStdnQ25/9lklWABRyAW2/w== dpb587-20160719a@dpb587-20160719a
  name: jump
  networks:
  - name: default
  persistent_disk_size: 1024
  stemcell: default
  vm_type: default
name: jump
releases:
- name: docker
  version: latest
- name: os-conf
  version: latest
- name: demo-jump
  version: latest
stemcells:
- alias: default
  os: ubuntu-trusty
  version: '3262.2'
update:
  canaries: 1
  canary_watch_time: 1000-60000
  max_in_flight: 1
  update_watch_time: 1000-60000
